### ISSUE TITLE
Verify spring security path

### ISSUE THREAD

**Issue by r-brown** [Labs64/NetLicensing-Gateway#11]
In the spring security configuration https://github.com/Labs64/NetLicensing-Gateway/blob/master/src/main/resources/context/security.xml#L15
the path `mycommerce/keygen` points to a non-exisiting endpoint.

- Is there any reason to define such path?
- how the real path is protected then: https://github.com/Labs64/NetLicensing-Gateway/blob/master/src/main/java/com/labs64/netlicensing/gateway/util/Constants.java#L29

**Comment by r-brown** [comment]
Implementation is not acceptable.
Which impact will be at the current integrations after this change?
Test?!?!?!

**Comment by yushkevich** [comment]
Authentication must be provided for the _mycommerce/codegen_

1. send mycommerce request without authentication
![2019-10-14_15-47-33](https://user-images.githubusercontent.com/3961540/66752656-942f1a80-ee9a-11e9-89b9-09260e1b8ddf.png)
2. send mycommerce request with the wrong authentication
![2019-10-14_15-49-02](https://user-images.githubusercontent.com/3961540/66752677-a446fa00-ee9a-11e9-8beb-1552c8617fe2.png)
3. send mycommerce request with the right authentication
![2019-10-14_15-47-33](https://user-images.githubusercontent.com/3961540/66752689-af018f00-ee9a-11e9-968f-351da78dca3d.png)

**Comment by r-brown** [comment]
> 3. send mycommerce request with the right authentication

fails with HTTP401 - why?

Why do we need integration specific entry in the global spring-security configuration?

**Comment by yushkevich** [comment]
3. send mycommerce request with the right authentication (it was wrong screenshot)
![2019-10-14_15-46-14](https://user-images.githubusercontent.com/3961540/66753668-f8eb7480-ee9c-11e9-9757-714674e9b951.png)

**Comment by yushkevich** [comment]
> Why do we need integration specific entry in the global spring-security configuration?
- there is no reason
1. send mycommerce request without authentication
![2019-10-14_16-37-30](https://user-images.githubusercontent.com/3961540/66755591-f854dd00-eea0-11e9-9da9-fe4a5be2e503.png)
2. send mycommerce request with the wrong authentication
![2019-10-14_16-37-09](https://user-images.githubusercontent.com/3961540/66755607-0145ae80-eea1-11e9-9b3d-6ee1ffe93709.png)
3. send mycommerce request with the right authentication
![2019-10-14_16-41-18](https://user-images.githubusercontent.com/3961540/66755836-7a450600-eea1-11e9-9f70-4c4bbaf36d93.png)
