### ISSUE TITLE
Refactor individual integrations in one single package

### ISSUE THREAD

**Issue by r-brown** [Labs64/NetLicensing-Gateway#19]
Current integrations implementation (e.g. MyCommerce) is distributed across several packages, which increases significantly the maintenance effort.
Following need to be considered:
- introduce the foundation (base) gateway classes
- move integration of specific classes in the dedicated package
  - every new implementation should be using the same pattern/structure
- avoid multiple configurations locations while enabling the new integration

Expected: a plug-in approach for enabling the new integrations.

**Comment by yushkevich** [comment]
MyCommerce was encapsulated.
