### ISSUE TITLE
Dockerize NetLicensing Gateway

### ISSUE THREAD

**Issue by r-brown** [Labs64/NetLicensing-Gateway#2]
Enable NetLicensing Gateway to start within Docker container.

Use Cases:
- local development
- on vendor's premises to connect with the [third-party e-commerce, ERP and CRM solutions](https://netlicensing.io/documentation/#usage-scenarios).

**Comment by kaaquist** [comment]
I might be able to help here.

**Comment by r-brown** [comment]
The message flow is defined as the following:

`E-Commerce/ext` -(fulfilment)-> `NetLicensing Gateway/local` -> `NetLicensing.IO/ext`

So to allow external systems to send WebHooks request to the local environment, we'd need to set up an external forwarding (e.g. using https://ngrok.com or similar).
Therefore docker-compose might be useful here to start several dependent containers: Gateway + ngrok

**Comment by r-brown** [comment]
Additionally, build & redeploy source code within the container is needed, to streamline development activities.
