### ISSUE TITLE
Enable FastSpring integration

### ISSUE THREAD

**Issue by yushkevich** [Labs64/NetLicensing-Gateway#21]
### Use Case:

Frontend e-commerce systems offer an excellent customer experience by providing _Subscription Management, Payment Options, Billing & Accounting, Analytics, Security & Compliance_.
ISV will be able to use NetLicensing Gateway integration with the chosen frontend e-commerce system to allow customers to acquire licenses for their products. After license(-s) acquisition, necessary assets will be created and assigned to the customer within [NetLicensing](https://netlicensing.io) system during the fulfilment process.

### Typical integration tasks:

- NetLicensing creates and delivers Customer number to be used as an identifier during the shopping process
- E-Commerce system triggers configured NetLicensing Gateway endpoint during the fulfilment process
- NetLicensing creates and assigns Licenses to the current Customer

### References:

- Typical e-commerce integration flow: https://github.com/Labs64/NetLicensing-Gateway#license-acquisition-flow
- Sample implementation (MyCommerce): https://github.com/Labs64/NetLicensing-Gateway/blob/master/src/main/java/com/labs64/netlicensing/gateway/controller/restful/MyCommerceController.java
- NetLicening RESTful API: https://www.labs64.de/confluence/x/pwCo
- NetLicensing test account: `demo:demo` or your own
- **E-commerce integration documentation:**
  - https://docs.fastspring.com/products-bundles-and-subscriptions/fulfillments

---

### Support

Feel free to contact us for support via:
- Email: netlicensing@labs64.com
- Telegram chat: https://t.me/netlicensing

**Comment by yushkevich** [comment]
Fulfillments: Remote Server Request need to be implemented. 

> In the Authentication section of the page, the Username and Password fields allow you to specify optional logon credentials that FastSpring will pass to your server with each license key generation request. You can optionally configure the script hosted by your server to ignore requests that don't include a valid logon.

The authentication header isn't sending for some reason. - The support email has sent.

**Comment by yushkevich** [comment]
Email log:

> Hello. 
>  
> I have a problem with fulfillment and authentification by Username and Password.
>  
> I configured product with «Generate a License» -> «Remote Server Request» option. I create fulfillment and in the Authentication section enter Username and Password. 
>  
> There is no auth header in this case. How can I get Username and Password on the server side? Maybe I missed something? 
>  
>  
> Kindest regards,
> Andrei Yushkevich

and the answer is: 

> Hi Andrei,
> 
> I am checking into this for you, and I'll let you know when I have an answer from an engineer.
> 
> Thanks,

**Comment by yushkevich** [comment]
> Hello Andrei,
> 
> I escalated this to our product team, and we will have to see what they say about this.  I will keep you posted.
> 
> Thanks,

answer:

> Thank you. Please, feel free to contact me for additional information. 
> 
> Kindest regards,
> Andrei Yushkevich

**Comment by yushkevich** [comment]
> Hello,
> 
> Our engineering team is still researching this, but it is logged and they are actively working on it.  So I 
> will go ahead and close this case.  Please watch future release notes for a fix.
> 
> Thanks

**Comment by yushkevich** [comment]
One more problem: Contextual does not have custom field capabilities on our end

> Hello.
> I have a problem with the new 'Contextual Commerce’ documentation. I am looking for a way to add Custom Field to my store (something like that https://support.fastspring.com/hc/en-us/articles/207438126-Adding-a-Custom-Field-such-as-a-Survey-to-an-Order-Completed-or-Order-Completed-one-per-product-Notification). But there is no way to do that.
> Could you help me find out how can I do it in the new console?

> Hello,
> 
> Contextual does not have custom field capabilities on our end, but instead provides methods where you could collect those items on your site and pass them into the order process
> https://docs.fastspring.com/integrating-with-fastspring/passing-and-capturing-custom-order-tags-and-product-attributes
> https://docs.fastspring.com/integrating-with-fastspring/store-builder-library/accessing-the-library-from-javascript
> 
> I hope this resolves your issue.  If you have no further questions, we will be solving this ticket and the the ticket will close in five days.
> 
> Luanne Albright
> FastSpring Support Team Lead

**Comment by r-brown** [comment]
@yushkevich we'd need to advise the vendor to use `tags` attribute in order to be able to pass `licenseeNumber` of an existing customer.
The attribute name should be documented and used in the Gateway to decide, whether a new Licensee will be created or acquired Licenses will be added to the provided Licensee (licenseeNumber)

**Comment by yushkevich** [comment]
@r-brown documentation is ready. FastSpring controller works as expected. 
Please review and merge with trunk.

**Comment by r-brown** [comment]
Documentation released at https://github.com/Labs64/NetLicensing-Gateway/wiki/FastSpring
